spring:
  application:
    name: user-api-gateway

grpc:
  client:
    product-service:
      address: 'static://localhost:9001'
      negotiation-type: plaintext
    order-service:
      address: 'static://localhost:9002'
      negotiation-type: plaintext
    inventory-service:
      address: 'static://localhost:9003'
      negotiation-type: plaintext

jwt:
  secret: 'v7S6A9yB2E5H8KcNfUjXnZr4u7x!A%D*G-'

server:
  port: 8100

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: healthz
      exposure:
        include: health,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

resilience4j:
  circuitbreaker:
    instances:
      product-cb:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
      inventory-cb:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
      order-cb:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true